image: docker:latest

services:
    - docker:dind

variables:
  # This should be set by docker image already, just to be sure...
  DOCKER_HOST: tcp://docker:2375
  # Use overlayfs driver for better performance
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1
  VERSION: "v0.0.16"

stages:
  - build
  - release

build-docker-image:
  stage: build
  image:
    name: torizonextras/pwsh-gitlab:latest

  variables:
    TASKS_ITERATIVE: "False"
    TASKS_OVERRIDE_ENV: "False"

  script: |
    echo '

      docker login -u matheuscastello -p $env:DOCKER_PSSWD
      ./.vscode/tasks.ps1 run build-container-torizon-release-amd64
      docker compose -f docker-compose.yml push torizon-emulator-manager

    ' | gitlabWrapper.ps1

  artifacts:
    paths:
      - install.sh
      - docker-compose.yml
      - torizon-emulator-manager

release-artifacts:
  stage: release
  needs:
    - build-docker-image
  image:
    name: registry.gitlab.com/gitlab-org/release-cli:latest

  script: |
    echo "Releasing version v$VERSION"

  release:
    tag_name: $VERSION
    description: Torizon Emulator Manager $VERSION
    assets:
      links:
        - name: install.sh
          url: $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_REF_NAME/raw/install.sh?job=build-docker-image
        - name: docker-compose.yml
          url: $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_REF_NAME/raw/docker-compose.yml?job=build-docker-image
        - name: torizon-emulator-manager
          url: $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_REF_NAME/raw/torizon-emulator-manager?job=build-docker-image
